### ISSUE TITLE
[BUG] Checkbox not visible in Splitter

### ISSUE THREAD

**Issue by edkirk30** [bczsalba/pytermgui#101]
**Describe the bug**
Checkbox not rendered correctly inside Splitter in 7.2.0. Works as expected in 7.1.0. Checkbox action does work via mouse if right co-ords clicked.

**To Reproduce**

```
        with ptg.WindowManager() as manager:
            window = (
                ptg.Window(
                    "",
                    ptg.Splitter(
                        ptg.Checkbox(), # isn't visible when not selected
                        ptg.Label("some label"),
                        ptg.Checkbox(), # isn't visible when not selected AND doesn't contribute space to layout until selected
                        ptg.Label("some label"),
                    ),
                   ptg.Checkbox(), # renders fine
                    "",
                    ptg.Button("Done", lambda *_: return),
                    width=80,
                    box="DOUBLE",
                )
                .set_title("[210 bold]Some Title")
                .center()
            )

            manager.add(window)

```

**Expected behavior**
Visible checkboxes :)

**Screenshots**

7.2.0
(nothing selected)
![image](https://user-images.githubusercontent.com/157594/199734125-d47fc403-adb0-4d1e-a6e4-8213e6b785fc.png)

(second checkbox selected)
![image](https://user-images.githubusercontent.com/157594/199734176-b1e3e90a-c11f-414d-b11b-f891260b8a65.png)

7.1.0
![image](https://user-images.githubusercontent.com/157594/199732961-d49df634-748c-415c-bec1-4c7f22a9ffea.png)

**System information**

```
PyTermGUI version 7.2.0

System details:
    Python version: 3.8.13
    $TERM:          xterm-256color
    $COLORTERM:     truecolor
    Color support:  ColorSystem.TRUE
    OS Platform:    Linux-5.15.0-39-generic-x86_64-with-glibc2.35
```

**Comment by bczsalba** [comment]
Should be fixed now, and the patch includes a snazzier look for checkboxes as well! Sorry about the delay.
