### ISSUE TITLE
Windows not working

### ISSUE THREAD

**Issue by BlackF0rest** [bczsalba/pytermgui#113]
Hi i just started using the library and it works fine when i run the code in the VSCode Terminal but if I just open the .py with python then it just outputs things like the following:

`                                         ←[0mContainer←[0m                                                   ←[0m←[90m │←[0m←[0m←[90m ║←[0m←[15;1H←[90m║ ←[0m←[0m←[90m│ ←[0m                                                     ←[0mstacks←[0m                                                     ←[0m←[90m │←[0m←[0m←[90m ║←[0m←[16;1H←[90m║ ←[0m←[0m←[90m│ ←[0m                                                   ←[0mvertically←[0m                                                   ←[0m←[90m │←[0m←[0m←[90m ║←[0m←[17;1H←[90m║ ←[0m←[0m←[90m└←[0m←[90m──────────────────────────────────────────────────────────────────────────────────────────────────────────────────←[0m←[90m┘←[0m←[0m←[90m ║←[0m←[18;1H←[90m║ ←[0m←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0mSplitter←[0m←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m←[0m←[90m | ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0mstacks←[0m←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m←[0m←[90m | ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0mhorizontally←[0m←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m ←[0m←[90m ║←[0m←[19;1H←[90m║ ←[0m←[0m←[90m←[0m                                                     ←[0m←[100m←[2m←[97m ▶ Open me ←[0m                                                    ←[0m←[90m←[0m←[0m←[90m ║←[0m←[20;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[21;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[22;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[23;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[24;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[25;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[26;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[27;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[28;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[29;1H←[90m║ ←[0m                                                          ←[0m                                                          ←[0m←[90m ║←[0m←[30;1H←[90m╚←[0m←[90m══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════←[0m←[90m╝←[0m←[?2026l`

**Comment by bczsalba** [comment]
This is the same issue as discussed in #99, so I think the solution should be the same too. Note that currently we don't have mouse support on Windows cmd.
