### ISSUE TITLE
[REQUEST] Python 3.8

### ISSUE THREAD

**Issue by jsergiu** [bczsalba/pytermgui#132]
Current annotations make the code and examples are compatible with python 3.10 and later only.

**Describe the solution you'd like**
I propose using the typing package for annotations and keep the syntax compatible with 3.8 at least. 

**Describe alternatives you've considered**
My projects are python 3.8 and I'm not able to upgrade. 

I'm happy to make a PR for that

**Comment by bczsalba** [comment]
AFAIK it should be compatible =>3.8, and the automated actions seem to be running fine: https://github.com/bczsalba/pytermgui/actions/runs/6094768095/job/16536965596

Have you tried installing and working with it? If so, do you get any errors?

**Comment by jsergiu** [comment]
I think it was something wrong with my setup, sorry about that.
