### ISSUE TITLE
[BUG] [WSL2] XTerm does not display "box drawing" characters (but other terminals do)

### ISSUE THREAD

**Issue by ajh123** [bczsalba/pytermgui#134]
**Describe the bug**
Not really a bug with pytermgui but more of an issue with my XTerm.
Special "box drawing" characters are not displayed in XTerm, but they are on the Windows Terminal

**To Reproduce**
Steps to reproduce the behaviour:

1. Download the [https://github.com/bczsalba/pytermgui/blob/master/examples/simple_app.py](simple_app.py) somewhere.
2. Open XTerm and navigate to the folder where the simple_app.py was saved
3. Open it with python
4. See problem
5. Try the same steps but using the Windows Terminal connected to WSL
6. No problem occurs

**Expected behavior**
XTerm displays all characters like the Windows Terminal connected to WSL the does.

**Screenshots**
| XTerm| Windows Terminal|
|--------|--------|
| ![image](https://github.com/bczsalba/pytermgui/assets/41990982/17d93537-3d2e-4d0d-a62a-7734b1e20b4a) | ![image](https://github.com/bczsalba/pytermgui/assets/41990982/9fe7468b-16e5-4246-b09b-977f2c721aef)| 

(Different background colours are expected)

**System information**

```
Add the output of "ptg --version" in this box.
```
```
$ ptg --version
PyTermGUI version 7.7.0

System details:
    Python version: 3.10.12
    $TERM:          xterm-256color
    $COLORTERM:     None
    Color support:  ColorSystem.EIGHT_BIT
    OS Platform:    Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.3
```

**Possible cause**
If you have a hunch on what might be causing this, please add it here.

My XTerm configuration, or just XTerm it self.

**Possible solution**
If you know a way we could fix this, please add it here.

Adding `case $TERM in xterm) TERM=xterm-256color;; esac` to the bottom of my `~/.bashrc` only makes XTerm support more colours, not "more characters".

**Comment by bczsalba** [comment]
This is likely a problem with xterm not supporting certain ranges of characters. I've run into it myself, but the only thing we could do is downgrade the experience for everyone else in order to support a project (xterm) that no one really should be using anymore.

Thanks for the report!
