### ISSUE TITLE
No documentation available

### ISSUE THREAD

**Issue by Juliandev02** [bczsalba/pytermgui#136]
The documentation for pytermgui at https://ptg.bczsalba.com/pytermgui.html no longer works, making it impossible to learn pytermgui. 
Has the documentation been postponed or what is going on? I can't find another good TUI libary for Python and I don't want to learn Rust or something for my project ...

**Comment by bczsalba** [comment]
Hey! It's available, but under https://ptg.bczsalba.com!

Just out of curiousity, where did you find that link? :)

**Comment by Juliandev02** [comment]
> Yikes, that's embarrassing.
> 
> Alas, it is fixed now. Thank you!

no problem ;)
