### ISSUE TITLE
Question regarding `ptg.InputField`

### ISSUE THREAD

**Issue by user9329** [bczsalba/pytermgui#137]
How do I access the entered values

**Comment by bczsalba** [comment]
`InputField.value` is what you're looking for :)

**Comment by user9329** [comment]
yes!, btw is there any way can click on labels??

**Comment by bczsalba** [comment]
Not really unfortunately, labels are meant to be unclickable by design. You could subclass Label and set `_selectables_length` to 1 to make it clickable (and thus available as `parent.selected`), but it won't get highlighted unless you implement that as well.

**Comment by user9329** [comment]
alr

**Comment by user9329** [comment]
is there any way I can make App reactive??
