### ISSUE TITLE
[HOWTO] How can I use the terminal widget?

### ISSUE THREAD

**Issue by agoodfellow123** [bczsalba/pytermgui#139]
I want to create an environment like the [Twin Terminal Window Manager](https://github.com/cosmos72/twin) for that I must understand how to use the terminal widget, I'm trying to spawn it with:

```
from pytermgui import WindowManager, Window, Terminal, widgets

manager = WindowManager()
terminal = widgets.Widget.terminal
window = (terminal)
manager.add(terminal)
manager.run()
```
however unfortunately that just gives me the `AttributeError: 'property' object has no attribute 'manager'` error. Can you please explain step by step what I'm doing wrong?

**Comment by bczsalba** [comment]
As @tritium21 said, the Terminal object is an interface to the terminal emulator PTG is running in - not an emulator itself. Creating a multiplexer (which is what you're looking for I think) with PTG is possible, though far from trivial. I've collected some SO sources for it for a different project, so if you're interested these are a starting point:

- https://stackoverflow.com/a/4417735

- https://stackoverflow.com/a/28319191

- https://stackoverflow.com/a/73451441
