### ISSUE TITLE
[BUG] not possible to resize window from the left side

### ISSUE THREAD

**Issue by pvmm** [bczsalba/pytermgui#14]
**Describe the bug**
Dragging left side of window moves right side of window, which might make it disappear completely.

**To Reproduce**
1. Click left side of window border
2. Drag it
3. The right side of window will try to follow the mouse cursor
4. If you drag it to the left, window will implode on itself and disappear

**Expected behavior**
Clicking on the left side of the window should activate resize on the left side of the window, while the right side remains still.

**System information**
PyTermGUI v1.1.0
Python: 3.10.1
Platform: Linux-5.15.11-200.fc35.x86_64-x86_64-with-glibc2.34
Git commit: e061977

**Possible cause**
Lack of testing all possible ways a window can resize?

**Comment by bczsalba** [comment]
Funnily enough, nothing should be happening from dragging on the left side! I have no idea why it even does anything, since I never implemented this behaviour. Thank you for the report!

**Comment by pvmm** [comment]
So I suppose this is not worth fixing since you closed it?

**Comment by bczsalba** [comment]
I actually fixed it when I closed the issue way back. The resize behavior has been majorly improved in all ways, so if you haven't been up to date with the library I really recommend trying it out.

**Comment by pvmm** [comment]
Sorry, I failed to the the committed attach. Will test it now!
