### ISSUE TITLE
Official Debian package

### ISSUE THREAD

**Issue by buhtz** [bczsalba/pytermgui#140]
Hello,
this is not request to upstream.

I just want to mention that I opened an official "Request to Package" at Debian. I will need this package as a dependency for my [own project](https://github.com/bit-team/backintime) in the future.

Debian manage requests to package via bug tickets:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1061236

**Comment by bczsalba** [comment]
Nice, this is great to see! If you need anything else beyond what is already provided make sure to let me know!
