### ISSUE TITLE
[BUG] Documentation site unavailable

### ISSUE THREAD

**Issue by developomp** [bczsalba/pytermgui#23]
**Describe the bug**
The site https://ptg.bczsalba.com can not be reached.
DNS propagation check fails too: https://dnschecker.org/#A/ptg.bczsalba.com

**To Reproduce**
1. Open browser
2. Visit https://ptg.bczsalba.com

**Expected behavior**
The documentation page should load

**Screenshots**
Too lazy

**System information**
Does not have to do with my system.
Checked with multiple browsers, on different device, with VPN, and on tor.
This is clearly an issue on the DNS' side.

**Possible cause**
Since https://bczsalba.com (without the ptg prefix) does load, this doesn't seem to be a issue where your ownership of the domain has expired. Maybe you messed up the DNS settings for ptg.bczsalba.com

**Possible solution**
Go to wherever you registered the domain and add the IP address of the server to ptg.bczsalba.com

**Comment by bczsalba** [comment]
Yup, seems my DNS provider wiped the entry for the `ptg` subdomain. I've updated the settings, so it should come back up soon. Very annoying issue.

**Comment by developomp** [comment]
Nice
