### ISSUE TITLE
[REQUEST] Use formatters

### ISSUE THREAD

**Issue by developomp** [bczsalba/PyTermGUI#27]
Use [prettier](https://github.com/prettier/prettier) for markdown and yaml files and [black](https://github.com/psf/black) for python files.

**Comment by bczsalba** [comment]
I do use `black` for python, and since the module itself doesn't really have any YAML files included I never found it important enough. I try to keep the example files pretty, however. Where did you experience problems with this?

**Comment by developomp** [comment]
This change is not necessarily for the users but for the contributors. So even if this will not change anything for how the library will be used, but it'll keep things consistent when this project gets more contributors. The formatters used are listed in the `CONTRIBUTING.md` file as well as other contributor guidelines.

**Comment by bczsalba** [comment]
That's really my biggest issue here, not having the contribution guidelines. I keep having to tell everyone about Pylint & Mypy, as well as `black`.

I do want to get it up soon, but at the moment I am focused on some other projects, hence the slowing down of commits recently.

**Comment by developomp** [comment]
Closed in pr #31
