### ISSUE TITLE
[REQUEST] Support SIGWINCH on Windows

### ISSUE THREAD

**Issue by bczsalba** [bczsalba/pytermgui#33]
**Is your feature request related to a problem? Please describe.**
The window size change signal (`SIGWINCH`) is not built into `signal`, and PyTermGUI just skips handling it on Windows machines.

**Describe the solution you'd like**
Some kind of implementation (hopefully up-to-par with UNIX) for resize events.

**Describe alternatives you've considered**
Creating an asynchronous monitoring loop (#19). Turns out it hangs the program.

**Is this feature present in other TUI products?**
It is in Textual, not sure about others.

**Additional context**
 We probably have to interact with the windows API (similar to how [Textual](https://github.com/Textualize/textual/blob/main/src/textual/drivers/win32.py) does it) This is probably a decently sizeable undertaking, and one that I myself cannot take on at the moment.

Any help would be greatly appreciated here!

**Comment by bczsalba** [comment]
This is not directly related, but [this](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) API could solve a lot of issues.

**Comment by Tired-Fox** [comment]
I don't see anything that would recreate the issue.

 Also, I have noticed the bug only happens when shrinking the size and works most of the time if not always when increasing the size.
