### ISSUE TITLE
[SUGGESTION] Add `Window` panel row

### ISSUE THREAD

**Issue by sdushantha** [bczsalba/pytermgui#4]
I had found the following symbols and thought of sharing them with you as you may find it useful for this project's UI.

```
— ❐ ✕
```
The symbols may not look so nice in this issue, but they do look nice in the terminal as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/27065646/145276333-871410d4-f623-47ad-9805-d2a8a8ec308d.png)

**Comment by bczsalba** [comment]
Thank you! That will actually be really useful later on, as I'm planning on adding support for window panel buttons. Not quite sure when that will be as of yet, but it shouldn't be _too hard_ to implement, as I've already gotten it to work as a prototype some months ago.

**Comment by bczsalba** [comment]
Just going to merge #12 into this issues as it is essentially the same thing. Not sure when I'll get to adding this, but I am planning on doing it.

**Comment by bczsalba** [comment]
The current state of the library doesn't really fly with this idea unfortunately. Splitters are too finicky to make work, and baking a custom widget for this is ugly.

Thank you for the suggestion, I will probably end up using the characters in a different, much nicer place :wink:
