### ISSUE TITLE
[BUG] Documentation is invalid

### ISSUE THREAD

**Issue by skorokithakis** [bczsalba/pytermgui#40]
The documentation snipped here is invalid Python code:

```
import pytermgui as ptg

with ptg.WindowManager() as manager:
    manager.add(
        ptg.Window()
        + "[wm-title]My first window!",
        + "",
        + ["Exit", lambda *_: manager.exit()],
    )

    manager.run()
```

Also, the examples on the front page are nice for illustrating the various ways of declaring an interface, but when trying to run them I was taken aback by the fact that a window wouldn't launch. I eventually found the `manager.add()` function, but it would be nice if that were in the README somewhere so people could quickly try the framework out.

**Comment by bczsalba** [comment]
Thank you for the reference! I updated the docs to fix the issue, but the docs will only be pushed with the next release, as some of the updates since 3.1.0 contain some changes that would be documented before they are pushed.
