### ISSUE TITLE
[BUG] Error on launch

### ISSUE THREAD

**Issue by jonnieey** [bczsalba/pytermgui#45]
**Describe the bug**
ptg raises error on launch after v4.3.0 update.

**To Reproduce**

1. Open terminal
2. run ptg
3. See error

**Expected behavior**
Launch ptg.

**Screenshots**
![2022-04-03-095653](https://user-images.githubusercontent.com/47189744/161415690-c492ce38-7a50-4893-a3ba-54593573c56a.png)

**System information**

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
PyTermGUI v4.3.0
 
Python: 3.10.4
Platform: Linux-5.16.14-arch1-1-x86_64-with-glibc2.35
```

**Comment by bczsalba** [comment]
_Should_ be fixed now, could you give it a try on the latest commit? Interestingly this issue doesn't happen on MacOS, so I never ran into it.

**Comment by jonnieey** [comment]
Cheers, I'll let you know if anything else pops up. Great framework btw.

**Comment by bczsalba** [comment]
Thank you!
