### ISSUE TITLE
[BUG] io.UnsupportedOperation error on launch

### ISSUE THREAD

**Issue by x10102** [bczsalba/pytermgui#46]
Launching PTG on Windows produces an "io.UnsupportedOperation" error.

**PTG Version**: 
4.3.1

**Python version**:
3.10

**Code:** 
Window using children as arguments example from README

**Screenshot:**

![image](https://user-images.githubusercontent.com/29236660/162261336-b846febd-a0fb-4b8b-938d-8bea95beb84f.png)

**Comment by x10102** [comment]
This seems to be exactly the same error as #45. However, both the 'error.errno' and 'error.winerror' attributes are None. 
If the error number is always None on Windows, this could be fixed with a simple OS check:

```
...
except OSError as error:
            if error.errno != errno.EINVAL and os.name != 'nt':
                raise
...
```

**Comment by bczsalba** [comment]
Yup, I figured it was. Kind of annoying that the error gives completely different errors between Linux and Windows, while working without an exception on MacOS. Could you try the fix you have above?

**Comment by x10102** [comment]
Just tried, it works.

**Comment by bczsalba** [comment]
Alright, will add it in the next release. It will either be a bugfix patch or come bundled with the next minor release, depending on how much time I have away from university over the weekend.

Thanks for the report!

**Comment by x10102** [comment]
Nice.
Thanks for the project btw, I love it.

**Comment by bczsalba** [comment]
Thank you! Btw, some very cool work is being done over at the compositor branch, which should massively improve drawing performance and general responsiveness.

Once that's done I'm planning on implementing a global color palette based on real life user testing. Exciting times!

**Comment by bczsalba** [comment]
Actually, while we are here, how is PTG working on Windows, and what is your specific config? Haven't really been able to test it over there yet, so I'm very interested in how things are.

**Comment by x10102** [comment]
I haven't really gotten started with the project yet, but I'll be sure to update you if there are any other issues.
