### ISSUE TITLE
[BUG] getch not working in InputField example

### ISSUE THREAD

**Issue by revilo951** [bczsalba/pytermgui#62]
**Describe the bug**
The InputField example from [here](https://ptg.bczsalba.com/pytermgui/widgets/interactive/input_field.html#InputField.__init__) doesn't work, produces a `NameError: name 'getch' is not defined`

**To Reproduce**

1. Create python file with the contents of the example
2. Run python file

**Expected behavior**
keyboard inputs would be printed.
note: `ptg -g` works as expected

**System information**

```
$ ptg --version
PyTermGUI version 6.1.0

System details:
    Python version: 3.10.4
    $TERM:          xterm-256color
    $COLORTERM:     truecolor
    Color support:  ColorSystem.TRUE
    OS Platform:    Linux-5.4.0-109-generic-x86_64-with-glibc2.31
```

**Possible cause**
No idea, sorry. I wish I could be of more help. Happy to test anything you should suggest though

**Possible solution**
As above

**Comment by bczsalba** [comment]
Pretend that instead of `getch` it says `ptg.getch`, lol, sorry about that. Thank you for the report!

**Comment by revilo951** [comment]
No probs, thanks for clearing that up.
