### ISSUE TITLE
[BUG] InputField appears two cursors when typing

### ISSUE THREAD

**Issue by DuckyMomo20012** [bczsalba/pytermgui#70]
**Describe the bug**
When I resize the window vertically or set vertical_align of Window to CENTER or BOTTOM, the InputField appeared with two cursors when typing or focusing.

**To Reproduce**

1. Create a Window with one InputField.
2. Run the app.
3. Resize the window vertically.
4. Click on InputField.
5. Typing.
6. See the error.

OR

1. Go to this replit sandbox: https://replit.com/join/weiqtjcppk-duongvinh
2. Run the app.
3. Resize the "Login" window vertically.
4. Click on InputField.
5. Typing.
6. See the error.

**Expected behavior**
Only one cursor moving on the screen.

**Screenshots**
![pytermgui](https://user-images.githubusercontent.com/64480713/173230355-393440b4-74fa-4954-8b3e-1b44b4069aea.png)

**System information**

```
PyTermGUI version 6.3.0

System details:
    Python version: 3.10.4
    $TERM:          xterm-256color
    $COLORTERM:     truecolor
    Color support:  ColorSystem.TRUE
    OS Platform:    Linux-5.15.0-37-generic-x86_64-with-glibc2.35
```

**Comment by bczsalba** [comment]
Yep, this is a thing unfortunately. Not quite sure _why_ it's happening, but it should be fixed in the near future!
