### ISSUE TITLE
[REQUEST] Can we have a Discord/ Slack group?

### ISSUE THREAD

**Issue by rushic24** [bczsalba/pytermgui#73]
Hi, Thanks for building such a beautiful library. I was wondering if we could have a chat community :)

**Comment by bczsalba** [comment]
Hey there! I personally don't trust myself to be able to moderate and keep the server up to date, but if other people are able to do it I would love to!

**Comment by Tired-Fox** [comment]
I don't mind starting and moderating a discord centered around pytermgui

**Comment by mgomersbach** [comment]
We can start with a non-official one, just to talk a bit.

**Comment by bczsalba** [comment]
I made a server earlier today, I'll do some sprucing up tomorrow and ping this thread when the link is out!

**Comment by bczsalba** [comment]
[Here](https://discord.gg/g4bqMvpG4U) it is!

A project icon is in the works, and will be used later for the server. The server is pretty barebones at the moment but its better than nothing :rocket:
