### ISSUE TITLE
[BUG] input_field.py: AssertionError: assert self._drag_start is not None

### ISSUE THREAD

**Issue by DuckyMomo20012** [bczsalba/pytermgui#75]
**Describe the bug**
- I got this error when I focus on an `InputField`, then drag the `Container` border (box) of another `InputField`. This error happens when I wrap the `InputField` with the `Container` widget.
- I have tested most types of boxes and still see this error, except the `EMPTY` box type.
- This error only happens when I focus (click the area inside the Container border) on the first `InputField` and then drag the border (box) of the second `InputField`. Note that it won't happen when I focus on the first `InputField` and then focus on the second `InputField`.
- It's strange that this error doesn't happen when I tested it on [Replit](https://replit.com/) 🤔, it only happens in my local environment. You can copy the snippet code below and test it on Replit.

**To Reproduce**

1. You can copy the snippet code below:
```python
import pytermgui as ptg

with ptg.WindowManager() as manager:
    ptg.boxes.ROUNDED.set_chars_of(ptg.Container)

    window = ptg.Window(
        ptg.Label("Email"),
        ptg.Container(ptg.InputField()),
        ptg.Label("Password"),
        ptg.Container(ptg.InputField()),
    )
    window.vertical_align = ptg.VerticalAlignment.TOP
    manager.add(window)
    manager.run()
```
> NOTE: The `Label` widget is just for separating the `InputField`, you can remove it.

2. Run the program.
3. Click your mouse on the `InputField` below the "Email" label. NOTE: area **inside** the `Container` border, not the border.
4. Then use your mouse **drag** down (or up/left/right) the bottom (or top/left/right) **border** of the `InputField` below the "Password" label. NOTE: drag the border, not the area inside the `Container` border.
5. See error.

**Expected behavior**
Nothing happens, because I just drag the border.

**Screenshots**
Error message:
![error message](https://user-images.githubusercontent.com/64480713/178642890-1a506982-336a-40d9-af0a-8749e0e0c35e.png)

**System information**

```
PyTermGUI version 6.4.0

System details:
    Python version: 3.10.4
    $TERM:          xterm-256color
    $COLORTERM:     truecolor
    Color support:  ColorSystem.TRUE
    OS Platform:    Linux-5.15.0-40-generic-x86_64-with-glibc2.35
```

**Comment by bczsalba** [comment]
Will look into this after the next version release, thank you!

P.S. Your project is the first full-fledged PTG application I've seen, and it looks great! Good job!

**Comment by bczsalba** [comment]
Should work now! Could you confirm?

**Comment by DuckyMomo20012** [comment]
> Should work now! Could you confirm?

Sorry for the late response, I tested with version 7.0.0 and the system information mentioned in the issue description, and I can see that the error is resolved 👌.
