### ISSUE TITLE
[BUG] Ctrl-C doesn't stop threads

### ISSUE THREAD

**Issue by Tired-Fox** [bczsalba/pytermgui#78]
**Describe the bug**
When running any graphics loop, using the compositor, and you execute a keyboard interrupt the thread that draws the window keeps going. Mainly found on windows 10. 

I tested this on Windows 11 and the issue doesn't exist.

**To Reproduce**
1. Use a Windows 10 machine
1. Use Windows Terminal or Alacritty
1. Run any of the examples
1. Press `CTRL-C` 
1. Program exits, but thread keeps drawing screen which traps the terminal in the window

**Expected behavior**
Program exits cleanly back to terminal prompt

**Screenshots**
![LockedInDrawWindow](https://user-images.githubusercontent.com/94603332/179989286-33f07c80-4ccb-47a5-98cb-24533da318be.gif)
The above gif shows a flash of text from the interrupt then another draw call.

![LockedInTerminalInterrupt](https://user-images.githubusercontent.com/94603332/179989331-d2aa52eb-26d5-4737-9714-64862a2dc322.gif)
The above image shows the successful interrupt but the terminal is trapped because of a thread still being active.

**System information**
* Windows 10
* Alacritty
* Windows Terminal

```
PyTermGUI version 6.4.0

System details:
    Python version: 3.10.5
    $TERM:          None
    $COLORTERM:     None
    Color support:  ColorSystem.STANDARD
    OS Platform:    Windows-10-10.0.19043-SP0
```

**Possible cause**
On Windows 10 a keyboard interrupt does not stop child threads and only stops the main thread.

**Possible solution**
Set thread to be a daemon. When a thread is set to be a daemon it will terminate when all non-daemon threads terminate. This means when the main thread terminates so will the child thread.

* [Thread Signature](https://docs.python.org/3/library/threading.html#threading.Thread)
* [Daemon Flag](https://docs.python.org/3/library/threading.html#threading.Thread.daemon)

Add `daemon=True` to where the compositor draw thread is created
``` python
165        Thread(name="CompositorDrawLoop", target=self._draw_loop, daemon=True).start()
```

I have tested this on the machine that had this bug and it fixed the problem.

> NOTE:
> I would like to add that making the different threads daemons may solve some other issues as well.

**Comment by bczsalba** [comment]
Will look into this, thank you!

> I would like to add that making the different threads daemons may solve some other issues as well.

Do you have any specific things in mind for this?

**Comment by Tired-Fox** [comment]
I duel boot windows and linux, so I don't mind going into the windows side and helping.

I may look into writing some Windows API hooks, let me know if you are interested in bringing this into the project.

**Comment by Tired-Fox** [comment]
I saw that you linked that in #33. I wouldn't mind writing something that can translate between linux and windows calls to make it universal. I can start a discussion as to keep this issue about the problem listed above.

**Comment by bczsalba** [comment]
@Tired-Fox could you test out if `daemon=True` fixes the issue on Windows? It seems to not have any adverse effect on MacOS, so it should be fine on Linux too.

**Comment by Tired-Fox** [comment]
I can test both Linux and Windows

**Comment by Tired-Fox** [comment]
@bczsalba It seems that it has no adverse effects for Linux. It also works on windows with no obvious side affects.

**Comment by bczsalba** [comment]
Can you test if this fixed the issue? :smile:
