### ISSUE TITLE
[BUG] Error when running command "ptg --version" with version 7.0.0

### ISSUE THREAD

**Issue by DuckyMomo20012** [bczsalba/pytermgui#89]
**Describe the bug**
I encounter an error when running the command `ptg --version` on PyTermGUI version 7.0.0

**To Reproduce**

1. Install PyTermGUI version 7.0.0
2. Run command:
```bash
ptg --version
```
3. See the error.

**Expected behavior**
An output with system information.

**Screenshots**
![error](https://user-images.githubusercontent.com/64480713/181044854-ff05a272-242c-46ef-b16a-afb77d5249b7.png)

**System information**

I can't provide the output of version 7.0.0.

But, here is the output from version **6.4.0**:

```
PyTermGUI version 6.4.0

System details:
    Python version: 3.10.4
    $TERM:          xterm-256color
    $COLORTERM:     truecolor
    Color support:  ColorSystem.TRUE
    OS Platform:    Linux-5.15.0-41-generic-x86_64-with-glibc2.35
```

**Comment by bczsalba** [comment]
Crikey, that's embarrassing! I'll figure out a fix shortly.
