### ISSUE TITLE
[BUG] Input field is missing the prompt

### ISSUE THREAD

**Issue by ChrisRamsayITV** [bczsalba/pytermgui#90]
**Describe the bug**
The prompt is missing from InputFields

**To Reproduce**
1. If I create an InputField with eg:
   `InputField(prompt="My Input")` only the input field is displayed - no prompt.

**Expected behavior**
A prompt should appear before the input field

**Screenshots**
![image](https://user-images.githubusercontent.com/42544939/181231576-45bbdbd8-0043-43d3-bef9-4f407a8ecc37.png)

**System information**

`ptg --version` is also broken :)
Using `v7.0.0` of pytermgui on Linux

This is a great project btw, thanks for creating it :+1:

**Comment by bczsalba** [comment]
> ptg --version is also broken :)

A fix for that is already included for the next patch, `7.1.0`, along with the re-introduction of field prompts & improved line breaking behaviour for the field's cursor!

> This is a great project btw, thanks for creating it 👍

Thank you for the kind words! Feel free to open any discussions or join our discord if you have any questions.
