### ISSUE TITLE
[BUG] Buttons inside a Splitter are not highlighted

### ISSUE THREAD

**Issue by AdreamCZ** [bczsalba/pytermgui#92]
**Describe the bug**
When a button is placed inside a Splitter its style does not change to _highlighted_ when it is selected or hovered over.

**To Reproduce**

1. Create a Splitter
2. Add a button to the Splitter
3. Hover over the button

**Expected behavior**
The style should change when hovered over

**System information**

```
PyTermGUI version 7.2.0

System details:
    Python version: 3.10.4
    $TERM:          xterm
    $COLORTERM:     None
    Color support:  ColorSystem.STANDARD
    OS Platform:    Linux-5.17.0-2-amd64-x86_64-with-glibc2.33
```

**Comment by bczsalba** [comment]
No idea why this happens! I'll look into it in the coming days.

P.S.: What terminal are you running to get standard colorsystem? You can most likely change the `xterm` value to get more colors displayed by the module :)

**Comment by AdreamCZ** [comment]
This is from Kitty terminal

**Comment by bczsalba** [comment]
Kitty as in 
https://github.com/kovidgoyal/kitty? Does kitty.conf overwrite the `TERM` variable?

**Comment by bk90** [comment]
I tried this with kitty (`TERM=xterm-kitty`), Alacritty (`TERM=alacritty`), xterm and gnome-terminal. It's the same behavior in all terminals.

And this does not only affect buttons. `InputField`s are also not highlighted.

**Comment by riks-jogi** [comment]
Has anyone figured out a work-around for this type of issue?
My current layout is pretty split-heavy so it would be nice to get working.

If I figure something out I'll post it here.

**Comment by bczsalba** [comment]
> Has anyone figured out a work-around for this type of issue?
> My current layout is pretty split-heavy so it would be nice to get working.
> 
> If I figure something out I'll post it here.

For the time being, you can use:

```python
ptg.Splitter.styles.fill = lambda _, item: item
```

This will overwrite the fill style to return the thing given to it, as opposed to trying to fill it in with some background color. There is a problem _somewhere_ in the chain of `StyleManager`  -> `MarkupFormatter` `MarkupLanguage` that causes this issue, but I haven't figured out where exactly.

P.S. The current splitters aren't great, but the upcoming major release will introduce something waaaay nicer to use instead, so look out! :)
