### ISSUE TITLE
[BUG] Example in `README.md` seems broken.

### ISSUE THREAD

**Issue by nicolaslesquoy** [bczsalba/pytermgui#93]
**Description**
When running the following example :
```python
import pytermgui as ptg

CONFIG = """
config:
    InputField:
        styles:
            prompt: dim italic
            cursor: '@72'
    Label:
        styles:
            value: dim bold

    Window:
        styles:
            border: '60'
            corner: '60'

    Container:
        styles:
            border: '96'
            corner: '96'
"""

with ptg.YamlLoader() as loader:
    loader.load(CONFIG)

with ptg.WindowManager() as manager:
    window = (
        ptg.Window(
            "",
            ptg.InputField("Balazs", prompt="Name: "),
            ptg.InputField("Some street", prompt="Address: "),
            ptg.InputField("+11 0 123 456", prompt="Phone number: "),
            "",
            ptg.Container(
                "Additional notes:",
                ptg.InputField(
                    "A whole bunch of\nMeaningful notes\nand stuff", multiline=True
                ),
                box="EMPTY_VERTICAL",
            ),
            "",
            ["Submit", lambda *_: submit(manager, window)],
            width=60,
            box="DOUBLE",
        )
        .set_title("[210 bold]New contact")
        .center()
    )

    manager.add(window)
```
I get the follwing error : `NameError: name 'submit' is not defined`.

**To Reproduce**

1. Save this file as `tui.py`
2. Run it with `python3 tui.py`
3. Click with your mouse on `[Submit]`

**Expected behavior**
I expected the program to end without any error.

**System information**

```
PyTermGUI version 7.2.0

System details:
    Python version: 3.10.4
    $TERM:          xterm-256color
    $COLORTERM:     None
    Color support:  ColorSystem.EIGHT_BIT
    OS Platform:    Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
```

**Possible cause**
The `submit` function is not defined. 

**Possible solution**
I need to find in the documentation where this function is defined to call it correctly.

**Comment by bczsalba** [comment]
Hey there! The method isn't defined in the code snippet, but as the text below the example says:

> This showcases the YAML-based config system, as well as some additional API. I recommended checking out the [source file](https://github.com/bczsalba/pytermgui/blob/master/utils/readme_scripts/contact.py) to see how the submit callback works.

There is a source file (which is used to generate the screenshot) in the repo, which does have this function. The reason it's not there is to avoid unnecessary clutter :)
