### ISSUE TITLE
[BUG] Chinese text length is miscalculated

### ISSUE THREAD

**Issue by Yooootsuba** [bczsalba/pytermgui#98]
In my case, I want to use Chinese texts to display some infomations, and that broke the box's side.

Does there any solutions for this? 

![Screenshot from 2022-09-22 16-35-59](https://user-images.githubusercontent.com/48445296/191700417-7feb8e05-335d-4211-ae85-d6f787b43d03.png)

**Comment by bczsalba** [comment]
Chinese characters are a bit hard to handle, since their Unicode representation doesn't clearly show their lengths. I will look into fixing this in the future, thanks for the report!

**Comment by Yooootsuba** [comment]
> Chinese characters are a bit hard to handle, since their Unicode representation doesn't clearly show their lengths. I will look into fixing this in the future, thanks for the report!

Thanks for your reply. Looking forward to your patches ! :smile:
